apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  namespace: local
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: eureka-server
    spec:
     containers:
     - name: eureka-server
       image: c568254965/eureka-center:v1.0
       tty: true
       ports:
       - containerPort: 6801
