apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: local
spec:
  type: NodePort
  ports:
       - port: 6801
         targetPort: 6801
         nodePort: 31801
  selector:
    app: eureka-server
