server:
  port: 6801


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  profiles:
    active: dev

---
spring:
  profiles: test

eureka:
  instance:
    hostname: csrr-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://csrr-eureka:6801/eureka
